refactor(flag): remove old approach for flagged proposals
snapshot-labs/snapshot-hub pull request #701
Opened 2023-10-08 18:16 UTC by Todmy

Remove backwards compatibility for fetching flagged proposals and flagged/verified spaces from Laser DB

2023-10-08 18:41 UTC, wa0x6e approved these changes
utAck

2023-10-08 19:49 UTC, bonustrack commented on src/graphql/operations/proposals.ts
> +    searchSql += ' AND p.flagged = 1)';
Was this tested?

2023-10-09 05:34 UTC, wa0x6e requested changes
tAck, works aside the 2 extra `)` in the sql query

2023-10-09 05:34 UTC, wa0x6e commented on src/graphql/operations/proposals.ts
> +    searchSql += ' AND p.flagged = 0)';
Extra `)`

2023-10-09 05:34 UTC, wa0x6e commented on src/graphql/operations/proposals.ts
> +    searchSql += ' AND p.flagged = 1)';
Extra `)`

2023-10-09 09:13 UTC, Todmy reviewed
fix(mysql): mistake in query

2023-10-09 09:13 UTC, Todmy reviewed
fix(mysql): mistake in query

2023-10-09 09:20 UTC, wa0x6e approved these changes
tAck

2023-10-10 08:19 UTC, merged